Repository Sabirindev/Group07, pull requests merged in 2021-08, with the labels that each got.

#9 Marina vel
  src/day01/HelloWorld.java
  src/day01/Variables.java
Labels: bug

#32 Created tc001 branched
  src/day4/HelloWorld.java
Labels: duplicate

#36 shokhzodLogin
  src/newpackagebyShokh/login.java
Labels: bug

#39 TC002 COde is completed.
  src/day4/Login.java
Labels: documentation
